name = "autorenta-payments-webhook"
main = "dist/index.js"
compatibility_date = "2024-12-20"
account_id = "5b448192fe4b369642b68ad8f53a7603"

env = { }

[vars]
SUPABASE_URL = "https://pisqjmoklivzpwufhscx.supabase.co"

[build]
command = "npm run build"

[[kv_namespaces]]
binding = "AUTORENT_WEBHOOK_KV"
id = "a2a12698413f4f288023a9c595e19ae6"
